"""add created_by and deletede_by in collection

Revision ID: 03bf3c61b2a1
Revises: 19939972eecc
Create Date: 2026-07-11 18:56:27.766151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03bf3c61b2a1'
down_revision: Union[str, Sequence[str], None] = '19939972eecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('collections', sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'deleted_by')
    op.drop_column('collections', 'created_by')
    # ### end Alembic commands ###
