"""updated_at and updated_by in collection

Revision ID: c3b7e46a9b5e
Revises: e4cb6edf68d0
Create Date: 2026-07-30 13:56:42.563385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c3b7e46a9b5e'
down_revision: Union[str, Sequence[str], None] = 'e4cb6edf68d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('collections', sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'updated_by')
    op.drop_column('collections', 'updated_at')
    # ### end Alembic commands ###
