"""add indexes for sorting and roles filter

Revision ID: c5e04d44a449
Revises: 0423b7b4babd
Create Date: 2026-08-07 07:49:44.034154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5e04d44a449'
down_revision: Union[str, Sequence[str], None] = '0423b7b4babd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collections_created_at'), 'collections', ['created_at'], unique=False)
    op.create_index(op.f('ix_collections_created_by'), 'collections', ['created_by'], unique=False)
    op.create_index(op.f('ix_collections_description'), 'collections', ['description'], unique=False)
    op.create_index(op.f('ix_collections_gulax_name'), 'collections', ['gulax_name'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_created_by'), 'documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_documents_description'), 'documents', ['description'], unique=False)

    op.execute("CREATE INDEX ix_collections_roles_gin ON collections USING gin (roles)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_description'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_collections_gulax_name'), table_name='collections')
    op.drop_index(op.f('ix_collections_description'), table_name='collections')
    op.drop_index(op.f('ix_collections_created_by'), table_name='collections')
    op.drop_index(op.f('ix_collections_created_at'), table_name='collections')
    # ### end Alembic commands ###
