"""document updated and created user log

Revision ID: cf1f872623b8
Revises: c3b7e46a9b5e
Create Date: 2026-07-30 15:06:58.478503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf1f872623b8'
down_revision: Union[str, Sequence[str], None] = 'c3b7e46a9b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_by')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_by')
    # ### end Alembic commands ###
